"""empty message

Revision ID: dfa9eee2382f
Revises: 5a901d3fd452
Create Date: 2024-05-12 03:01:36.239530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfa9eee2382f'
down_revision = '5a901d3fd452'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Sex', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('Short_info', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('Position', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_column('Position')
        batch_op.drop_column('Short_info')
        batch_op.drop_column('Sex')

    # ### end Alembic commands ###
